name: Config Direct Save
core_version_requirement: ^8 || ^9 || ^10 || ^11
description: This module allow you to export configuration after changes
type: module
package: Deployment

# Information added by Drupal.org packaging script on 2024-03-16
version: '3.0.2'
project: 'config_direct_save'
datestamp: 1710625627
