unprotected_forms:
  - user_login_form
  - search_form
  - search_block_form
  - views_exposed_form
  - honeypot_settings_form
protect_all_forms: true
log: true
element_name: postcode
time_limit: 5
expire: 300
form_settings:
  user_register_form: true
  user_pass: true
  webforms: true
  contact_message_personal_form: true
  node_article_form: false
  node_file_browser_form: false
  node_gift_form: false
  node_magazine_form: false
  node_page_form: false
  node_webform_form: true
  comment_comment_form: false
_core:
  default_config_hash: jEhrePho9bAz_8-E-zPMXvlx4knpphzUdaiQJX-xc8Q
