<?php
/**
 * @file
 * Bootstrap sub-theme.
 *
 * Place your custom PHP code in this file.
 */

// Adds page node ID as a class
function aspirational_preprocess_html(&$variables) {
  $path = \Drupal::service('path.current')->getPath();
  $path_args = explode('/', $path);
  if (isset($path_args[1]) && isset($path_args[2]) && ($path_args[1] == 'node') && (is_numeric($path_args[2]))) {
    $variables['attributes']['class'][] = 'page-node-' . $path_args[2];
  }
}


// Add content type suggestions, e.g. page--node--article.html.twig.
function aspirational_theme_suggestions_page_title_alter(array &$suggestions, array $variables) {
  $node = \Drupal::routeMatch()->getParameter('node');
  if (!empty($node) && is_object($node)) {
    $suggestions[] = 'page_title__node';
    $suggestions[] = 'page_title__node__' . $node->getType();
  }
}

/**
 * Implements hook_theme_suggestions_HOOK_alter().
 */
function aspirational_theme_suggestions_image_alter(array &$suggestions, array $variables) {
  if ($variables['alt'] == 'UK Map') {
    $suggestions[] = 'image__uk__map';
  }
  elseif ($variables['alt'] == 'Inspi Aspi Map') {
    $suggestions[] = 'image__inspi__aspi__map';
  }
  elseif ($variables['alt'] == 'Inspi London Map') {
    $suggestions[] = 'image__inspi__london__map';
  }
}
